### PR TITLE
Created ComboBox Component

### PR DESCRIPTION
**Pull request by borozcod**
Created ComboBox Component. Missing arrow functionality. Fixes issue #14

### CODE REVIEW

**Comment by borozcod** [comment]
It seems like codeclimate is just complaining that many of our testing files are the same. Could this be a warning that gets ignored?

**Comment by michael-martin-al** [comment]
@borozcod let me know if you need anything else for this PR, of if it is ready to review.

**Comment by borozcod** [comment]
@michael-martin-al This component is at a good place for review. The only thing I was concerned about was that since I am doing a custom drop-down, for the arrow functionality I would have to add an event listener in `componentDidMount` and remove it on `componentWillUnmount`. Do you have any thoughts on this, maybe a different approach?

**Comment by michael-martin-al** [comment]
This looks good. For the arrow support, could you use `onKeyPress` or `onKeyDown`? Then, you wouldn't have to worry about the event listener when mounting/unmounting. You don't want to create a global listener. That could cause problems if you have more than one of these components on the screen at once.

**Comment by borozcod** [comment]
@michael-martin-al in this latest commit I updated from master to include all the `YVAuth` functionality and API. On the verse assignment page, I was having some issues with some components not rendering. On development, I commented out lines 93 to 108 to be able to work on my components (I uncommented this before committing). After talking with @alex-gale I was able to download the `@youversion/tupos-auth` npm module by adding a `.npmrc` file to the root of the project. In this commit, I've also added `.npmrc`  to `.gitignore`. Let me know if this is the correct approach.

**Comment by michael-martin-al** [comment]
I'm glad @alex-gale was able to help. Does the `.npmrc` file have the token in it? Or does it just have `$NPM_TOKEN` placeholder? It's probably a good idea to include the `.npmrc` file in the repo to help others who experience the same issue. We just don't want the token anywhere in the repo.

**Comment by borozcod** [comment]
I have the token as `${NPM_TOKEN}` which is stored in my environment variables. I'll go ahead and update the `.gitignore` file to include `.npmrc`.

**Comment by michael-martin-al** [comment]
This looks good to me @borozcod! Nice work! 💯 There may be some follow up work once designers start using it, but I think it's great for an MVP.

**Comment by michael-martin-al** [comment]
Fixes #14

**Pull request merged**
